
# Use an official Node.js runtime as a parent image
FROM node:17 as build

# Set the working directory to /app/frontend
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the container
COPY package*.json .

# Install frontend dependencies
RUN npm install

# Copy the rest of your frontend application to the container
COPY . .

# Build your frontend application (e.g., using Vite)
CMD ["npm","run","dev"]


# # Use a lightweight Nginx image to serve your frontend
# FROM nginx:alpine

# # Copy the built frontend code from the previous build stage
# COPY --from=build /app/frontend/dist /usr/share/nginx/html

# RUN npm run dev

# Expose port 80
EXPOSE 5173

# The Nginx container will automatically start serving your frontend
